


var lng = {
	sign_up:'Sign up',
	sign_in:'Sign in',
	back_home:'Back home',
	email_placeholder:'Email address',
	password_placeholder:'Password',
	date_birth_placeholder:'Date of birth',
	place_birth_placeholder:'Place of birth',
	confirm_password_placeholder:'Confirm password',
	name_placeholder:'Name',
	last_name_placeholder:'Last name',
	country_placeholder:'Country',
	remember_me_text:'Remember me',
	welcome_title_text:'Welcome to ToSala Workspace',
	login_message:'Authentication failed, please check your email and password!',
	language:'en',
	sign_up_message:'Sorry, this user already exists please check your information.',
	error_404_title:'404, Not found!',
	error_404_text:'Information you searched does not exists or has been removed!',
	log_out:'Log out',
	edit_text:'Edit',
	home:'Home',
	profil:'Profile',
	my_profil:'My profile',
	my_profil_lower:'my profile',
	change_password:'Change password',
	changed_password_text:'Password successfully changed!',
	old_password:'Old password',
	new_password:'New password',
	confirm_new_password:'Confirm new password',
	old_password_wrong:'Wrong password, please check it.',
	remove_account:'Delete account',
	delete_account_text:'Account successfully deleted!',
	delete_account_worng:'We cannot delete your account now, please try again later.',
	already_have_account:'I already have an account',
	need_account:'I don\'t have an account',
	update_account_text:'Account successfully updated!',
	update_account_wrong:'We cannot update your account now, please try again later.',
	profil_photo:'Profile photo',
	select_image:'Select an image',
	update_photo_text:'Profile photo successfully updated!',
	update_photo_wrong:'We cannot update your photo now, please try again later.',
	welcome_msg:'Welcome!',
	work_sapce_text:'Workspace',
	delete_text_button:'Delete',
	back_top:'Back to top',
	top_bar_link:'Home',
	top_bar_workspace:'Workspace',
	top_bar_forum:'Community',
	top_bar_search:'Research',
	bottom_link:'Invite friends',
	notification:'Notification',
	group_mention:'Group(s)',
	groups_not_found:'You don\'t have groups\ncreate one',
	top_bar_projects:'Project',
	create_group:'Create a group',
	create_group_btn:'Create group',
	create_group_input_group:'Group name',
	create_group_input_member:'Add Member ex: xxxx@to-sala.com',
	create_group_success_text:'Group successfully created!',
	create_community:'Create a community',
	create_community_btn:'Create community',
	create_community_input_group:'Community name',
	created_by_text:'Created by',
	created_on:'New project',
	last_projects:'Last 3 projects',
	members:'Members',
	add_member:'Add member',
	task_list:'Tasks list',
	add_task:'Add task',
	me:'You',
	no_member:'No member',
	rename_group_success_text:'Group successfully renamed!',
	error_text:'We occurred an error, please try again!',
	create_group_info_text:'You can add member in your group only if he has an account to notify him.',
	create_community_info_text:'Every communities are public',
	user_does_not_exists:'This user does not exists and cannot be added as member',
	invitation_sent:'Your invitation is successfully sent',
	invited_you:'Hi, i invite you to join group',
	notif_not_found:'Notification not found',
	invit_not_found:'Invitation not found',
	new_invitation:'New invitation',
	invitation_text:'Invitation',
	from:'From',
	agree_button:'AGREE',
	reject_button:'REJECT',
	rejectedMessage:'You rejected this invitation',
	agreedMessage:'You agreed this invitation\nCongratulation! You are now a member of this group',
	existingMember:'This member already exists',
	your_current_projects:'Your projects',
	your_current_project:'Your project',
	your_current_project_folder:'Your folder',
	public_project:'Public projects',
	create_project:'Create a project',
	create_project_btn:'Create project',
	see_user_projects:'See my projects',
	close_text:'Close',
	remove_text:'Remove',
	do_you_remove_text:'Do you want to remove',
	create_project_input_name:'Project name',
	create_project_description:'Description',
	create_project_success_text:'Project successfully created!',
	create_community_success_text:'Community successfully created!',
	private_project:'Private',
	public_project_text:'Public',
	individual_project:'Individual',
	group_project_text:'Group',
	range_project_text:'Project range',
	projects_not_found:'You don\'t have projects\ncreate one',
	only_domain:'Only my domain',
	privacy_text:'Privacy',
	terms_text:'Terms',
	like_button:'Like',
	dislike_button:'Dislike',
	comment_button:'Comment',
	recommend_button:'Recommend',
	leave_group_success_text:'You successfully left this group!',
	start_here_text:'Start here!',
	are_you_sure_question: 'Are you sure?',
	view_details_text: 'View details',
	loading_text:'Loading...',
	what_they_say_text:'What they say ?',
	creation_date_text:'Date of creation',
	online_text:'online',
	no_public_project_text:'There is no project',
	group_deleted:'Project successfully deleted',
	leave_text:'Leave',
	overview_text:'Overview',
	follow_text:'Follow',
	unfollow_text:'Unfollow',
	tags_text:'Tags',
	tags_text_ex:'ex: JavaScript;',
	stats_text:'Stats',
	community_welcome_text:'Welcome to community',
	most_voted_text:'Most voted',
	popular_text:'Popular',
	best_articles_text:'News list',
	suggestion_text:'Suggestions',
	latest_articles_text:'Latest articles',
	domains_text:'Domains',
	archies_text:'Archives',
	activity_text:'Activities:',
	like_text:'Likes:',
	follower_text:'Followers:',
	comments_text:'Comments:',
    by_text:'by',
    cannot_set_private_public_text:'You cannot define this project individual and public at the same time.',
    your_communities_text:'Your communities',
    read_more_text:'Read more',
    title_publishing_article: 'Title...',
    comment_publishing_article: 'Enter comment...',
    publish_button:'Publish',
    write_something_text:'Share something...',
    written_text:'written',
    seconds_text:'seconds',
    minute_ago:'1 minute ago',
    minute_from_now:'1 minute from now',
    minutes_text:'minutes',
    hour_ago:'1 hour ago',
    hour_from_now:'1 hour from now',
    hours_text:'hours',
    yesterday_text:'Yesterday',
    tomorrow_text:'Tomorrow',
    days_text:'days',
    last_weeks_text:'Last week',
    next_month_text:'Next week',
    weeks_text:'weeks',
    just_now_text:'Just now',
    from_now_text:'from now',
    ago_text:'ago',
    last_month_texts: 'Last month',
    next_month_texts: 'Next month',
    months_texts: 'months',
    last_year_texts: 'Last year',
    next_year_texts: 'Next year',
    years_texts: 'years',
    last_century_texts: 'Last century',
    next_century_texts: 'Next century',
    centuries_texts: 'centuries',
    setting_text: 'Settings',
	site_description: 'Working together for a better World!',
    search_text: 'Search'
};

var links = {
	sign_up_link:'register',
	sign_in_link:'login',
	home_link:'/',
	connected_link:'connected',
	forum_home_link:'community',
    forum_overview_link:'overview',
	link_home_link:'links',
    link_home_search:'search',
	project_home_link:'projects',
    dashboard_project_home_project:'projects',
	dashboard_forum_home_link:'community',
	dashboard_link_home_link:'links',
	log_out_link:'log_out'
};
exports.en = lng;
exports.link = links;