

var prefix = 'fr/';
var lng = {
	sign_up:'Inscription',
	sign_in:'Connexion',
	back_home:'Retour vers l\'accueil',
	email_placeholder:'Adresse mail',
	password_placeholder:'Mot de passe',
	date_birth_placeholder:'Date de naissance',
	place_birth_placeholder:'Lieux de naissance',
	confirm_password_placeholder:'Confirmer votre mot de passe',
	country_placeholder:'Pays',
	name_placeholder:'Nom',
	last_name_placeholder:'Prenom',
	remember_me_text:'Se souvenir de moi',
	welcome_title_text:'Bienvenue à l\'espace ToSala',
	login_message:'Mauvaise authentification, veuillez vérifier votre email et votre mot de passe !',
	language:prefix.replace('/', ''),
	sign_up_message:'Désolé, cet utilisateur existe veuillez vérifier vos coordonnées!',
	error_404_title:'404, Non trouvé !',
	error_404_text:'L\'information que vous recherchiez n\'éxiste pas ou a été supprimée !',
	log_out:'Déconnexion',
	edit_text:'Modifier',
	home:'Accueil',
	profil:'Profil',
	my_profil:'Mon profil',
	my_profil_lower:'mon profil',
	change_password:'Changer mot de passe',
	changed_password_text:'Mot de passe changé avec succès !',
	old_password:'Ancien mot de passe',
	new_password:'Nouveau mot de passe',
	confirm_new_password:'Confirmer nouveau mot de passe',
	old_password_wrong:'Mauvais mot de passe, veuillez le vérifier.',
	remove_account:'Supprimer compte',
	delete_account_text:'Compte supprimé avec succès !',
	delete_account_worng:'Nous ne pouvons pas supprimer votre compte, Veuillez réessayer.',
	already_have_account:'Je possède un compte',
	need_account:'Je n\'ai pas de compte',
	update_account_text:'Compte modifié avec succès !',
	update_account_worng:'Nous ne pouvons pas modifier votre compte, Veuillez réessayer.',
	profil_photo:'Photo de profil',
	select_image:'Selectionner une image',
	update_photo_text:'Photo de profil changé avec succès !',
	update_photo_worng:'Nous ne pouvons pas changer votre photo, Veuillez réessayer.',
	welcome_msg:'Bienvenue !',
	work_sapce_text:'Espace de travail',
	delete_text_button:'Supprimer',
	back_top:'Retourner en haut',
	top_bar_link:'Liens',
	top_bar_workspace:'Espace de travail',
	top_bar_forum:'Communauté',
	top_bar_search:'Recherche',
	bottom_link:'Inviter les amis',
	notification:'Notification',
	group_mention:'Groupe(s)',
	groups_not_found:'Vous n\'avez pas de groupes\ncréez-en un',
	top_bar_projects:'Projet',
	create_group:'Créer un groupe',
	create_group_btn:'Créer groupe',
	create_group_input_group:'Nom du groupe',
	create_group_input_member:'Ajouter un membre ex: xxxx@to-sala.com',
	create_group_success_text:'Groupe créé avec succès !',
	create_community:'Créer une communauté',
	create_community_btn:'Créer communauté',
	create_community_input_group:'Nom de la communauté',
	created_by_text:'Créé par',
	created_on:'Nouveau projet',
	last_projects:'Les 3 derniers projets',
	members:'Membres',
	add_member:'Ajouter membre',
	task_list:'Liste de tâches',
	add_task:'Ajouter tâche',
	me:'Vous',
	no_member:'Pas de membre',
	rename_group_success_text:'Groupe renommé avec succès !',
	error_text:'Nous avons rencontré un problème, Veuillez réessayer !',
	create_group_info_text:'Vous pouvez ajouter un membre dans votre groupe si ce dernier possède un compte pour le notifier.',
	create_community_info_text:'Toutes les communautés sont public',
	user_does_not_exists:'Cet utilisateur n\'éxiste pas et ne peut être ajouté comme membre',
	invitation_sent:'Votre invitation est envoyée avec succès',
	invited_you:'Salut, je vous invite à rejoindre le groupe',
	notif_not_found:'Vous n\'avez pas de notification',
	invit_not_found:'Vous n\'avez pas d\'invitation',
	new_invitation:'Nouvelle invitation',
	invitation_text:'Invitation',
	from:'De',
	agree_button:'ACCEPTER',
	reject_button:'REJETER',
	rejectedMessage:'Vous avez rejeté l\'invitation',
	agreedMessage:'Vous avez accepté cette invitation\nFélicitation ! Vous êtes maintenant un membre de ce groupe',
	existingMember:'Ce membre éxiste',
	your_current_projects:'Vos projets',
	your_current_project:'Votre projet',
	your_current_project_folder:'Votre dossier',
	public_project:'Projets public',
	create_project:'Créer un projet',
	create_project_btn:'Créer projet',
	see_user_projects:'Voir tous mes projets',
	close_text:'Fermer',
	remove_text:'Retirer',
	do_you_remove_text:'Voulez-vous retirer',
	create_project_input_name:'Nom du projet',
	create_project_description:'Description',
	create_project_success_text:'Projet créé avec succès !',
	create_community_success_text:'Communauté créée avec succès !',
	private_project:'Privé',
	public_project_text:'Public',
	individual_project:'Individuel',
	group_project_text:'Groupe',
	range_project_text:'Portée du projet',
	projects_not_found:'Vous n\'avez pas de projets\ncréez-en un',
	only_domain:'Seulement Mon domaine',
	privacy_text:'Politique de confidentialité',
	terms_text:'Condition d\'utilisation',
	like_button:'J\'aime',
	dislike_button:'J\'aime pas',
	comment_button:'Commenter',
	recommend_button:'Recommander',
	leave_group_success_text:'Vous venez de quitter le groupe avec succès !',
	start_here_text:'Commencer !',
	are_you_sure_question: 'Êtes vous sûr ?',
	view_details_text: 'Voir les détails',
	loading_text:'Chargement...',
	no_public_project_text:'Pas de projet',
	creation_date_text:'Date de création',
	online_text:'en ligne',
	what_they_say_text:'Que disent-ils ?',
	group_deleted:'Projet supprimé avec succès !',
	leave_text:'Quitter',
    overview_text:'Vue d\'ensemble',
    follow_text:'Suivre',
	unfollow_text:'Ne plus suivre',
    tags_text:'Tags',
	tags_text_ex:'ex : JavaScript;',
    stats_text:'Stats',
    community_welcome_text:'Bienvenue à la communauté',
    most_voted_text:'Les plus votés',
    popular_text:'Populaire',
    best_articles_text:'Fil d\'actualité',
    suggestion_text:'Suggestions',
    latest_articles_text:'Derniers articles',
    domains_text:'Domaines',
    archies_text:'Archives',
    activity_text:'Activités :',
    like_text:'Aimes :',
    follower_text:'Abonnés :',
    comments_text:'Commentaires :',
    by_text:'par',
    cannot_set_private_public_text:'Vous ne pouvez definir ce projet individuel et public en même temps.',
    your_communities_text:'Vos communautés',
    read_more_text:'Lire la suite',
    title_publishing_article: 'Titre...',
    comment_publishing_article: 'Entrer un commentaire...',
    publish_button:'Publier',
    write_something_text:'Ecrivez quelque chose...',
    written_text:'écrit',
    seconds_text:'secondes',
    minute_ago:'il y a 1 minute',
    minute_from_now:'il y a 1 minute',
    minutes_text:'minutes',
    hour_ago:'il y a 1 heure',
    hour_from_now:'il y a 1 heure',
    hours_text:'heures',
    yesterday_text:'Hier',
    tomorrow_text:'Demain',
    days_text:'jours',
    last_weeks_text:'semaine dernière',
    next_month_text:'semaine prochaine',
    weeks_text:'semaines',
    just_now_text:'A l\'instant',
    from_now_text:'maintenant',
    ago_text:'il y a',
    last_month_texts: 'Dernier mois',
    next_month_texts: 'Prochain mois',
    months_texts: 'mois',
    last_year_texts: 'Année dernière',
    next_year_texts: 'Année prochaine',
    years_texts: 'année',
    last_century_texts: 'Siècle dernier',
    next_century_texts: 'Prochain siècle',
    centuries_texts: 'siècle',
    setting_text: 'Paramètres',
    site_description: 'Ensemble travaillons pour un monde meilleur !',
	search_text: 'Recherche'
};

var links = {
	sign_up_link:prefix+'register',
	sign_in_link:prefix+'login',
	home_link:'/'+prefix.replace('/', ''),
	connected_link:prefix+'connected',
	dashboard_forum_home_link:'community',
	dashboard_link_home_link:'links',
    dashboard_project_home_project:'projects',
	forum_home_link:prefix+'community',
    forum_overview_link:'overview',
	link_home_link:prefix+'links',
	project_home_link:prefix+'projects',
    link_home_search:prefix+'search',
	log_out_link:prefix+'log_out'
};
exports.fr = lng;
exports.link = links;